
package main;


import java.io.IOException;
import javax.swing.JFrame;

/**
 *
 * @author grzet
 */
public class Home extends javax.swing.JFrame {      //namesto update nardit subscription ali vpisi studenta .. 
                                                    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);  //fullscreen 
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelGlavnoOkno = new javax.swing.JPanel();
        jpanelZgornjiPanel = new javax.swing.JPanel();
        jlblExit = new javax.swing.JLabel();
        jlblsistemUpravljanja1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jlblsistemUpravljanja2 = new javax.swing.JLabel();
        jlblsistemUpravljanja3 = new javax.swing.JLabel();
        jlblMinimize = new javax.swing.JLabel();
        jpanelEmail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpanelStudenti = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpanelUrnik = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpanelOceneStud = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpanelOcene = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpanelMenu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(1, 1, 300, 400));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jpanelGlavnoOkno.setBackground(new java.awt.Color(255, 255, 255));
        jpanelGlavnoOkno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelZgornjiPanel.setBackground(new java.awt.Color(25, 112, 176));
        jpanelZgornjiPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblExit.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jlblExit.setForeground(new java.awt.Color(255, 255, 255));
        jlblExit.setText("X");
        jlblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlblExitMousePressed(evt);
            }
        });
        jpanelZgornjiPanel.add(jlblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 0, -1, -1));

        jlblsistemUpravljanja1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jlblsistemUpravljanja1.setForeground(new java.awt.Color(255, 255, 255));
        jlblsistemUpravljanja1.setText("Šole");
        jpanelZgornjiPanel.add(jlblsistemUpravljanja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 90));

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(0, 0, 0));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jpanelZgornjiPanel.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 459, 39));

        jButton1.setBackground(new java.awt.Color(25, 112, 176));
        jButton1.setForeground(new java.awt.Color(153, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/Zoom-icon.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpanelZgornjiPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 60, -1));

        jLabel13.setText("WEB SEARCH");
        jpanelZgornjiPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 90, -1));

        jlblsistemUpravljanja2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jlblsistemUpravljanja2.setForeground(new java.awt.Color(255, 255, 255));
        jlblsistemUpravljanja2.setText("Sistem ");
        jpanelZgornjiPanel.add(jlblsistemUpravljanja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 150, 70));

        jlblsistemUpravljanja3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jlblsistemUpravljanja3.setForeground(new java.awt.Color(255, 255, 255));
        jlblsistemUpravljanja3.setText("Upravljanja");
        jpanelZgornjiPanel.add(jlblsistemUpravljanja3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, 90));

        jlblMinimize.setBackground(new java.awt.Color(255, 255, 255));
        jlblMinimize.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jlblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jlblMinimize.setText("-");
        jlblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblMinimizeMouseClicked(evt);
            }
        });
        jpanelZgornjiPanel.add(jlblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 0, 30, 40));

        jpanelGlavnoOkno.add(jpanelZgornjiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 1920, 330));

        jpanelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jpanelEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelEmailMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/emial.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("E-mail");

        javax.swing.GroupLayout jpanelEmailLayout = new javax.swing.GroupLayout(jpanelEmail);
        jpanelEmail.setLayout(jpanelEmailLayout);
        jpanelEmailLayout.setHorizontalGroup(
            jpanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelEmailLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
            .addGroup(jpanelEmailLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelEmailLayout.setVerticalGroup(
            jpanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEmailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jpanelGlavnoOkno.add(jpanelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 640, -1, -1));

        jpanelStudenti.setBackground(new java.awt.Color(255, 255, 255));
        jpanelStudenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpanelStudentiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpanelStudentiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelStudentiMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/Student-3-icon.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Študenti");

        javax.swing.GroupLayout jpanelStudentiLayout = new javax.swing.GroupLayout(jpanelStudenti);
        jpanelStudenti.setLayout(jpanelStudentiLayout);
        jpanelStudentiLayout.setHorizontalGroup(
            jpanelStudentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelStudentiLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jpanelStudentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpanelStudentiLayout.setVerticalGroup(
            jpanelStudentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelStudentiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        jpanelGlavnoOkno.add(jpanelStudenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 110, -1));

        jpanelUrnik.setBackground(new java.awt.Color(255, 255, 255));
        jpanelUrnik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpanelUrnikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpanelUrnikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelUrnikMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/Apps-preferences-system-time-icon.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Urnik");

        javax.swing.GroupLayout jpanelUrnikLayout = new javax.swing.GroupLayout(jpanelUrnik);
        jpanelUrnik.setLayout(jpanelUrnikLayout);
        jpanelUrnikLayout.setHorizontalGroup(
            jpanelUrnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelUrnikLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jpanelUrnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelUrnikLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jpanelUrnikLayout.setVerticalGroup(
            jpanelUrnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelUrnikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jpanelGlavnoOkno.add(jpanelUrnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 440, 180, -1));

        jpanelOceneStud.setBackground(new java.awt.Color(255, 255, 255));
        jpanelOceneStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelOceneStudMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/OceneStud.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ocene Študentov");

        javax.swing.GroupLayout jpanelOceneStudLayout = new javax.swing.GroupLayout(jpanelOceneStud);
        jpanelOceneStud.setLayout(jpanelOceneStudLayout);
        jpanelOceneStudLayout.setHorizontalGroup(
            jpanelOceneStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelOceneStudLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(jpanelOceneStudLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelOceneStudLayout.setVerticalGroup(
            jpanelOceneStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelOceneStudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jpanelGlavnoOkno.add(jpanelOceneStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 170, 120));

        jpanelOcene.setBackground(new java.awt.Color(255, 255, 255));
        jpanelOcene.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpanelOceneMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelOceneMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpanelOceneMouseReleased(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/classes.jpg"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Baza Študentov");

        javax.swing.GroupLayout jpanelOceneLayout = new javax.swing.GroupLayout(jpanelOcene);
        jpanelOcene.setLayout(jpanelOceneLayout);
        jpanelOceneLayout.setHorizontalGroup(
            jpanelOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelOceneLayout.createSequentialGroup()
                .addGroup(jpanelOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelOceneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jpanelOceneLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelOceneLayout.setVerticalGroup(
            jpanelOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelOceneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        jpanelGlavnoOkno.add(jpanelOcene, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 650, 150, -1));

        jpanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpanelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpanelMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpanelMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelMenuMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/menu.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Menu");

        javax.swing.GroupLayout jpanelMenuLayout = new javax.swing.GroupLayout(jpanelMenu);
        jpanelMenu.setLayout(jpanelMenuLayout);
        jpanelMenuLayout.setHorizontalGroup(
            jpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMenuLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)))
                .addGap(21, 21, 21))
        );
        jpanelMenuLayout.setVerticalGroup(
            jpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12))
        );

        jpanelGlavnoOkno.add(jpanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        jPanel1.setBackground(new java.awt.Color(25, 112, 176));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1930, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jpanelGlavnoOkno.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 790, 1930, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelGlavnoOkno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelGlavnoOkno, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(2027, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlblExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblExitMousePressed
       System.exit(0);                                                          //gre ven iz aplikacije
    }//GEN-LAST:event_jlblExitMousePressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jpanelMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelMenuMouseEntered

    private void jpanelMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelMenuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelMenuMouseExited

    private void jpanelStudentiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelStudentiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelStudentiMouseEntered

    private void jpanelStudentiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelStudentiMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelStudentiMouseExited

    private void jpanelUrnikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelUrnikMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelUrnikMouseEntered

    private void jpanelUrnikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelUrnikMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelUrnikMouseExited

    private void jpanelOceneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelOceneMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelOceneMouseExited

    private void jpanelMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelMenuMousePressed
       new Menu().show();                              //prikaze frame ko klikes na panel 
    }//GEN-LAST:event_jpanelMenuMousePressed

    private void jpanelStudentiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelStudentiMousePressed
      ;   new LoginPassword().show();                       //prikaze frame ko klikes na panel 
    }//GEN-LAST:event_jpanelStudentiMousePressed

    private void jpanelUrnikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelUrnikMousePressed
        new Urnik1().show();
    }//GEN-LAST:event_jpanelUrnikMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String web = search.getText().replace(" ","+");                                     //replace zaradi pisanja v brskalnik(jtextfield)
        try{
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("http://www.google.com/search?hl=en&q="+web+"&btnG=Google+Search"));   //povezava z google...
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 
       
    private void jpanelOceneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelOceneMousePressed
            new BazaStudentov().show();
            
    }//GEN-LAST:event_jpanelOceneMousePressed

    private void jpanelOceneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelOceneMouseReleased
      
        
    }//GEN-LAST:event_jpanelOceneMouseReleased

    private void jpanelOceneStudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelOceneStudMousePressed
      new OceneStudenti().show();
       

               
    }//GEN-LAST:event_jpanelOceneStudMousePressed

    private void jpanelEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelEmailMouseClicked
         try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("https://mail.google.com/mail/u/0/#inbox"));   //povezava direkt na email(v tem primeru gmail v inbox)
        } catch (IOException e) {
           
        }
    }//GEN-LAST:event_jpanelEmailMouseClicked

    private void jlblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMinimizeMouseClicked
        this.setState(this.ICONIFIED); //minimiraj okno
    }//GEN-LAST:event_jlblMinimizeMouseClicked
public void setColor(JPanel panel)
        { 
        panel.setBackground(new java.awt.Color(115,163,239));           //barva panela ozadje 
                    }
public void resetColor(JPanel panel)
        { 
        panel.setBackground(new java.awt.Color(240,240,240));
                    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblExit;
    private javax.swing.JLabel jlblMinimize;
    private javax.swing.JLabel jlblsistemUpravljanja1;
    private javax.swing.JLabel jlblsistemUpravljanja2;
    private javax.swing.JLabel jlblsistemUpravljanja3;
    private javax.swing.JPanel jpanelEmail;
    private javax.swing.JPanel jpanelGlavnoOkno;
    private javax.swing.JPanel jpanelMenu;
    private javax.swing.JPanel jpanelOcene;
    private javax.swing.JPanel jpanelOceneStud;
    private javax.swing.JPanel jpanelStudenti;
    private javax.swing.JPanel jpanelUrnik;
    private javax.swing.JPanel jpanelZgornjiPanel;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
